### PR TITLE
added current pins from napari-svg repo

### PR DESCRIPTION
**Pull request by k-dominik**
This is related to https://github.com/conda-forge/napari-feedstock/issues/7
The changes would ideally go into the 0.1.3 version (as I haven't tracked back the pins for the 0.1.2) (so into https://github.com/conda-forge/napari-svg-feedstock/pull/1)

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by k-dominik** [comment]
@conda-forge-admin, please rerender

**Comment by jni** [comment]
@k-dominik I merged #1, would you mind rebasing this?

As mentioned on conda-forge/napari-feedstock#7, I'm reluctant to merge these restrictions until they've actually caused an issue, but that's certainly the case for the vispy version at that feedstock.

It would be great if @jakirkham or @ocefpaf could comment on what the best policy is with respect to version limits on conda-forge recipes.

**Comment by k-dominik** [comment]
oh, sorry - sure will do

**Comment by jakirkham** [comment]
In the very beginning of conda-forge, we more often stripped the version constraints than kept them. This was in part due to overly tight dependencies often made to guarantee tested versions showed up in an environment (even without a solver). The Python community has since grown from there and dependencies in packages are generally more reliable. So we try to honor them in conda-forge where possible. Adding the version constraints here makes sense to me if this is what `napari-svg` requires. Though I'll defer to Juan on that decision :)

**Comment by jni** [comment]
Sorry this fell through the cracks @k-dominik but I expect you found a suitable workaround... 😅

**Pull request closed without merging**
